
const keywordScores={"gia đình":5,"cha mẹ":5,"bố mẹ":5,"anh em":4,"bạn thân":4,"sức khỏe":5,"bản thân":5,"bình yên":5,"tương lai":4,"ước mơ":4,"lòng tốt":5,"tử tế":5,"tự do":4,"trung thực":4,"học":4,"thi":3,"làm việc":4,"nỗ lực":4,"mục tiêu":4,"điểm cao":3,"thành công":3,"học bổng":4,"tự học":4,"rèn luyện":4,"kiến thức":4,"thời gian":3,"cải thiện":3,"bạn bè":3,"người yêu":3,"tình bạn":3,"kết nối":3,"gia sư":3,"bị bỏ rơi":1,"bị quên":1,"một mình":2,"không ai hiểu":2,"chia tay":2,"like":1,"follow":1,"trend":1,"hot":1,"viral":1,"được chú ý":1,"so sánh":1,"người khác":1,"bị tụt lại":1,"thua kém":1,"đi sau":1,"fomo":1,"sự kiện":2,"đi chơi":2,"bình an":5,"vui vẻ":4,"hạnh phúc":5,"biết ơn":5,"thư giãn":4,"ngủ ngon":4,"thảnh thơi":4,"tự tin":5,"nhẹ nhõm":5,"an yên":5,"lo lắng":1,"sợ":1,"bỏ lỡ":1,"áp lực":1,"mệt mỏi":1,"kiệt sức":1,"buồn":2,"tức giận":1,"ghen tị":1,"bồn chồn":1,"stress":1};
function getSentenceScore(s){if(!(s=(s||"").toLowerCase().trim()))return 0;let e=0;for(const[t,n]of Object.entries(keywordScores))s.includes(t)&&(e+=n);return s.length>=30&&(e+=1),e||2}
const $=e=>document.querySelector(e),$$=e=>Array.from(document.querySelectorAll(e));
function createInput(){const e=document.createElement("div");e.className="row";const t=document.createElement("input");t.type="text",t.className="inp",t.placeholder="Nhập điều bạn đang sợ bỏ lỡ…";const n=document.createElement("button");n.className="ghost",n.type="button",n.textContent="Xoá",n.onclick=()=>e.remove(),e.appendChild(t),e.appendChild(n),$(".inputs").appendChild(e),t.focus()}
function createBubble(e,t,n="normal"){const o=document.createElement("div");return o.className="bubble"+("big"===n?" big":"small"===n?" small":""),o.textContent=e||"...",o.style.left=`calc(${t}% - ${"big"===n?"84":"65"}px)`,o.style.animationDelay=`${.05+1.2*Math.random()}s`,$(".sky").appendChild(o),o}
function popBubble(e){e&&(e.classList.add("pop"),setTimeout(()=>e.remove(),800));try{const e=new(window.AudioContext||window.webkitAudioContext),t=e.createOscillator(),n=e.createGain();t.type="triangle",t.frequency.value=520,n.gain.setValueAtTime(.07,e.currentTime),n.gain.exponentialRampToValueAtTime(.0001,e.currentTime+.14),t.connect(n).connect(e.destination),t.start(),t.stop(e.currentTime+.15)}catch{}}
function keepBubble(e){e&&e.classList.add("keep")}
function showModal(e){const t=$(".modal");$(".modal .content").innerHTML=e,t.classList.add("show")}function closeModal(){$(".modal").classList.remove("show")}
document.addEventListener("DOMContentLoaded",(()=>{$("#add").addEventListener("click",createInput),$("#go").addEventListener("click",runFilter),$("#reset").addEventListener("click",resetAll),$("#close").addEventListener("click",closeModal);for(let e=0;e<3;e++)createInput()}));
function readInputs(){return $$(".inp").map((e=>e.value.trim())).filter(Boolean)}
function runFilter(){$(".result").innerHTML="",$(".sky").innerHTML="",closeModal();const e=readInputs();if(0===e.length)return void($(".result").innerHTML='<span class="tip">Hãy viết ít nhất 1 điều để Tầng Không lọc giúp bạn.</span>');const t=e.map((e=>({text:e,score:getSentenceScore(e)}))),n=[],o=[];t.forEach((e=>{e.score>=4?n.push(e):o.push(e)}));const i=t.length,r=Array.from({length:i},((e,t)=>6+88/((i-1)||1)*t));t.forEach(((e,t)=>{const i=e.score>=6?"big":e.score<4?"small":"normal",s=createBubble(e.text,r[t],i);e.score>=4?setTimeout((()=>keepBubble(s)),1500+600*Math.random()):setTimeout((()=>popBubble(s)),1700+1200*Math.random())}));const s=n.map((e=>`“${e.text}”`)).join(", "),a=o.map((e=>`“${e.text}”`)).join(", ");let l="";if(0===n.length)l="Có vẻ những điều bạn vừa nêu đang thuộc vùng phù du – dư âm của so sánh và ồn ào bên ngoài. Hãy hỏi tim mình: điều gì còn lại nếu không cần chứng minh với ai?";else{const e=n.reduce(((e,t)=>e+t.score),0)/n.length;const t=e>=6?"Đó là gốc rễ của bạn – giá trị, sức khỏe, những điều dài lâu. Chăm sóc chúng bằng sự kiên nhẫn; không cần chạy đua.":"Chúng đủ quan trọng để bạn dành sự chú ý, nhưng vẫn có thể đi từng bước nhỏ, nhẹ nhàng.";l=`Sau tất cả, ${s} là những điều quan trọng nhất dành cho bạn ngay lúc này. ${t}`}const d=o.length?`<br><br>Những nỗi sợ còn lại (${a}) chỉ là phù du — chúng không cần phải ở lại trong đầu bạn nữa.`:"";setTimeout((()=>{showModal(`\n      <h3>Sau tất cả…</h3>\n      <p>${l}${d}</p>\n      <p>Nếu bạn muốn biết cách <b>chăm sóc những điều quan trọng</b> vừa hiện ra, hãy trò chuyện với <b>FOMO Buddy</b> để nhận hướng dẫn cụ thể.</p>\n      <div class="cta">\n        <a class="btn" href="#" onclick="alert('Bạn có thể gắn link chatbot FOMO Buddy ở đây.');return false;">Mở FOMO Buddy</a>\n        <button onclick="closeModal()">Đóng</button>\n      </div>\n    `)}),2600)}
function resetAll(){$(".inputs").innerHTML="";for(let e=0;e<3;e++)createInput();$(".sky").innerHTML="";$(".result").textContent="",closeModal()}
