
const keywordScores={"gia đình":5,"cha mẹ":5,"bố mẹ":5,"anh em":4,"bạn thân":4,"sức khỏe":5,"bản thân":5,"bình yên":5,"tương lai":4,"ước mơ":4,"lòng tốt":5,"tử tế":5,"tự do":4,"trung thực":4,"học":4,"thi":3,"làm việc":4,"nỗ lực":4,"mục tiêu":4,"điểm cao":3,"thành công":3,"học bổng":4,"tự học":4,"rèn luyện":4,"kiến thức":4,"thời gian":3,"cải thiện":3,"bạn bè":3,"người yêu":3,"tình bạn":3,"kết nối":3,"gia sư":3,"bị bỏ rơi":1,"bị quên":1,"một mình":2,"không ai hiểu":2,"chia tay":2,"like":1,"follow":1,"trend":1,"hot":1,"viral":1,"được chú ý":1,"so sánh":1,"người khác":1,"bị tụt lại":1,"thua kém":1,"đi sau":1,"fomo":1,"sự kiện":2,"đi chơi":2,"bình an":5,"vui vẻ":4,"hạnh phúc":5,"biết ơn":5,"thư giãn":4,"ngủ ngon":4,"thảnh thơi":4,"tự tin":5,"nhẹ nhõm":5,"an yên":5,"lo lắng":1,"sợ":1,"bỏ lỡ":1,"áp lực":1,"mệt mỏi":1,"kiệt sức":1,"buồn":2,"tức giận":1,"ghen tị":1,"bồn chồn":1,"stress":1};
function getSentenceScore(e){if(!(e=(e||"").toLowerCase().trim()))return 0;let t=0;for(const[n,o]of Object.entries(keywordScores))e.includes(n)&&(t+=o);return e.length>=30&&(t+=1),t||2}
const $=e=>document.querySelector(e),$$=e=>Array.from(document.querySelectorAll(e));
function createInput(){const e=document.createElement("div");e.className="row";const t=document.createElement("input");t.type="text",t.className="inp",t.placeholder="Nhập điều bạn đang sợ bỏ lỡ…";const n=document.createElement("button");n.className="ghost",n.type="button",n.textContent="Xoá",n.onclick=()=>e.remove(),e.appendChild(t),e.appendChild(n),$(".inputs").appendChild(e),t.focus()}
function createBubble(e,t,n="normal"){const o=document.createElement("div");return o.className="bubble"+("big"===n?" big":"small"===n?" small":""),o.textContent=e||"...",o.style.left=`calc(${t}% - ${"big"===n?"88":"69"}px)`,o.style.animationDelay=`${.1+1.4*Math.random()}s`,$(".sky").appendChild(o),o}
function popBubble(e){return e?(e.classList.add("pop"),new Promise((t=>setTimeout((()=>{e.remove(),t()}),900)))):Promise.resolve()}
function keepBubble(e){return e&&e.classList.add("keep"),new Promise((e=>setTimeout(e,2e4)))}
function showModal(e){const t=$(".modal");$(".modal .content").innerHTML=e,t.classList.add("show")}function closeModal(){$(".modal").classList.remove("show")}
document.addEventListener("DOMContentLoaded",(()=>{$("#add").addEventListener("click",createInput),$("#go").addEventListener("click",runFilter),$("#reset").addEventListener("click",resetAll),$("#close").addEventListener("click",closeModal);for(let e=0;e<3;e++)createInput()}));
function readInputs(){return $$(".inp").map((e=>e.value.trim())).filter(Boolean)}
async function runFilter(){$(".result").innerHTML="",$(".sky").innerHTML="",closeModal();const e=readInputs();if(0===e.length)return void($(".result").innerHTML='<span class="tip">Hãy viết ít nhất 1 điều để Tầng Không lọc giúp bạn.</span>');const t=e.map((e=>({text:e,score:getSentenceScore(e)}))),n=[],o=[];t.forEach((e=>{e.score>=4?n.push(e):o.push(e)}));const i=t.length,r=Array.from({length:i},((e,t)=>6+88/((i-1)||1)*t)),s=[];t.forEach(((e,t)=>{const i=e.score>=6?"big":e.score<4?"small":"normal",a=createBubble(e.text,r[t],i);e.score>=4?s.push(keepBubble(a)):s.push(new Promise((t=>{setTimeout((async()=>{await popBubble(a),t()}),2200+1800*Math.random())})))})),await Promise.all(s);const a=n.map((e=>`“${e.text}”`)).join(", "),l=o.map((e=>`“${e.text}”`)).join(", ");let c="";c=n.length?`Sau tất cả, ${a} là điều quan trọng nhất dành cho bạn ngay lúc này. Mình ở đây và tin bạn có thể đi từng bước nhỏ — ghi lại, thở đều, làm điều gần nhất trong tầm tay. Nỗi sợ không phải kẻ thù; nó là tín hiệu. Khi bạn chăm nó bằng sự kiên nhẫn, nó sẽ hóa thành sức bật.`:"Sau tất cả, những điều vừa thả có lẽ đang ở vùng phù du của tâm trí — nhiều tiếng ồn hơn là sự thật. Thử hỏi trái tim: nếu không cần chứng minh gì với ai, thì bạn còn muốn giữ điều gì lại?";l&&(c+=` <br><br>Những nỗi sợ còn lại ${l?`(${l})`:""} chỉ là màn sương đi qua. Bạn không phải ôm hết chúng đâu.`),c+=" Có rất nhiều người trước bạn cũng từng thả những bong bóng như vậy — và rồi họ đã vượt qua.";const d='<a class="btn" href="https://www.facebook.com/profile.php?id=61580386329472" target="_blank" rel="noopener">Trò chuyện với FOMO Buddy</a>';showModal(`\n    <h3>Nhắn riêng cho bạn</h3>\n    <p>${c}</p>\n    <p>Nếu muốn biến điều quan trọng này thành thói quen hằng ngày, mình đã chuẩn bị một người bạn đồng hành.</p>\n    <div class="cta">${d}<button onclick="closeModal()">Đóng</button></div>\n  `)}
function resetAll(){$(".inputs").innerHTML="";for(let e=0;e<3;e++)createInput();$(".sky").innerHTML="";$(".result").textContent="",closeModal()}
